collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.1218638
color:
  saturation: 0.8513211
  brandStrength: 0.7181739
  rhythmicContrast: 0.6344516
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  lightness: 0.7150537
layout_spectrum: 0
name: Nguyen-Ventura
